# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
kind: Template
apiVersion: v1
metadata:
  labels:
    app: rhche
  name: rhche
  annotations:
    description: Che
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: rhche
    name: rhche
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rhche
    name: rhche-host
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: rhche
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: rhche
    name: rhche
  spec:
    to:
      kind: Service
      name: rhche-host
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: rhche
    name: rhche
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: rhche
    strategy:
      type: ${STRATEGY}
    template:
      metadata:
        labels:
          app: rhche
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CHE_MULTIUSER
            valueFrom:
              configMapKeyRef:
                key: multi-user
                name: rhche
          - name: CHE_HOST
            value: "che-${NAMESPACE}.${ROUTING_SUFFIX}"
          - name: CHE_PORT
            value: "8080"
          - name: CHE_API
            value: "${PROTOCOL}://che-${NAMESPACE}.${ROUTING_SUFFIX}/api"
          - name: CHE_WEBSOCKET_ENDPOINT
            value: "${WS_PROTOCOL}://che-${NAMESPACE}.${ROUTING_SUFFIX}/api/websocket"
          - name: CHE_DEBUG_SERVER
            valueFrom:
              configMapKeyRef:
                key: remote-debugging-enabled
                name: rhche
          - name: CHE_INFRASTRUCTURE_ACTIVE
            value: "openshift"
          - name: CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL
            value: "${PROTOCOL}://che-${NAMESPACE}.${ROUTING_SUFFIX}/agent-binaries/linux_amd64/bootstrapper/bootstrapper"
          - name: CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN
            valueFrom:
              configMapKeyRef:
                key: infra-machine-start-timeout
                name: rhche
          - name: CHE_INFRA_OPENSHIFT_PROJECT
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CHE_INFRA_KUBERNETES_PVC_STRATEGY
            valueFrom:
              configMapKeyRef:
                key: infra-pvc-strategy
                name: rhche
          - name: CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS
            valueFrom:
              configMapKeyRef:
                key: che-openshift-precreate-subpaths
                name: rhche
          - name: CHE_INFRA_OPENSHIFT_TLS__ENABLED
            valueFrom:
              configMapKeyRef:
                key: che-openshift-secure-routes
                name: rhche
          - name: CHE_INFRA_KUBERNETES_TRUST__CERTS
            valueFrom:
              configMapKeyRef:
                key: infra-trust-certs
                name: rhche
          - name: CHE_LOCAL_CONF_DIR
            valueFrom:
              configMapKeyRef:
                key: local-conf-dir
                name: rhche
          - name: CHE_LOGS_DIR
            valueFrom:
              configMapKeyRef:
                key: che.logs.dir
                name: rhche
          - name: CHE_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                key: log-level
                name: rhche
          - name: CHE_KEYCLOAK_AUTH__SERVER__URL
            value: "${CHE_KEYCLOAK_AUTH__SERVER__URL}"
          - name: JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                key: che-server-java-opts
                name: rhche
          - name: CHE_WORKSPACE_AUTO__START
            valueFrom:
              configMapKeyRef:
                key: enable-workspaces-autostart
                name: rhche
          - name: CHE_KEYCLOAK_CLIENT__ID
            valueFrom:
              configMapKeyRef:
                key: che-keycloak-client-id
                name: rhche
          - name: CHE_KEYCLOAK_OIDC__PROVIDER
            valueFrom:
              configMapKeyRef:
                key: che-keycloak-oidc-provider
                name: rhche
          - name: CHE_KEYCLOAK_USE__NONCE
            valueFrom:
              configMapKeyRef:
                key: che-keycloak-use-nonce
                name: rhche
          - name: CHE_WORKSPACE_STORAGE
            valueFrom:
              configMapKeyRef:
                key: workspace-storage
                name: rhche
          - name: CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS
            valueFrom:
              configMapKeyRef:
                key: che.workspace.agent.dev.inactive_stop_timeout_ms
                name: rhche
          - name: CHE_LIMITS_WORKSPACE_ENV_RAM
            valueFrom:
              configMapKeyRef:
                key: workspaces-memory-limit-max
                name: rhche
          - name: CHE_WORKSPACE_DEFAULT__MEMORY__MB
            valueFrom:
              configMapKeyRef:
                key: workspaces-memory-limit
                name: rhche
          - name: CHE_WORKSPACE_JAVA__OPTIONS
            valueFrom:
              configMapKeyRef:
                key: che-workspaces-java-opts
                name: rhche
          - name: CHE_KEYCLOAK_GITHUB_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: keycloak-github-endpoint
                name: rhche
          - name: CHE_FABRIC8_MULTITENANT
            valueFrom:
              configMapKeyRef:
                key: che-fabric8-multitenant
                name: rhche
          - name: CHE_FABRIC8_USER__SERVICE_ENDPOINT
            value: ${CHE_FABRIC8_USER__SERVICE_ENDPOINT}
          - name: CHE_FABRIC8_AUTH_ENDPOINT
            value: ${CHE_FABRIC8_AUTH_ENDPOINT}
          - name: CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL
            value: ${CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL}
          - name: CHE_WORKSPACE_LOGS_ROOT__DIR
            valueFrom:
              configMapKeyRef:
                key: che-workspace-logs
                name: rhche
          - name: CHE_KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                key: che-keycloak-realm
                name: rhche
          - name: CHE_JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.password
                  name: rhche
          - name: CHE_JDBC_URL
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.url
                  name: rhche
          - name: CHE_JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                  key: che.jdbc.username
                  name: rhche
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                  key: service.account.secret
                  name: rhche
          - name: CHE_OPENSHIFT_SERVICE__ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                  key: service.account.id
                  name: rhche
          - name: CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD
            valueFrom:
              configMapKeyRef:
                key: che-workspace-server-ping-success-threshold
                name: rhche
          - name: CHE_LIMITS_USER_WORKSPACES_RUN_COUNT
            valueFrom:
              configMapKeyRef:
                key: che-limits-user-workspaces-run-count
                name: rhche
          - name: PROTOCOL
            value: "${PROTOCOL}"
          - name: ROUTING_SUFFIX
            value: "${ROUTING_SUFFIX}"
          - name: CHE_OAUTH_SERVICE__MODE
            value: "embedded"
          image: ${IMAGE_CHE}:${CHE_VERSION}
          imagePullPolicy: "${PULL_POLICY}"
          livenessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 60
          name: rhche
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8000
            name: http-debug
          - containerPort: 8888
            name: jgroups-ping
            protocol: TCP
          resources:
            limits:
              memory: 750Mi
            requests:
              memory: 256Mi
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
        restartPolicy: Always
        serviceAccountName: rhche
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange

parameters:
- name: ROUTING_SUFFIX
  displayName: Routing suffix of your OpenShift cluster
  description: This is the suffix appended to routes in your OpenShift cluster <route>-<project>.<routing_suffix>
- name: CHE_VERSION
  displayName: Eclipse Che version
  description: Eclipse Che version which defaults to nightly
  value: latest
- name: IMAGE_CHE
  displayName: Eclipse Che server image
  description: Che server Docker image. Defaults to docker.io/eclipse/che-server
  value: registry.devshift.net/che/rh-che-server
- name: PROTOCOL
  displayName: https or http protocol
  description: Protocol to be used in Che communications
  value: http
- name: WS_PROTOCOL
  displayName: wss or ws
  description: Websocket protocol to be used in Che communications. Defaults to ws. Set to wss only if TLS is true and https protocol is defined
  value: ws
- name: CHE_KEYCLOAK_AUTH__SERVER__URL
  displayName: Identity provider URL
  description: URL of a remote identity provider. Defaults to Keycloak bundled with Che multi user
  value: '${PROTOCOL}://keycloak-${NAMESPACE}.${ROUTING_SUFFIX}/auth'
- name: STRATEGY
  displayName: Update Strategy
  description: Che server update strategy. Defaults to Recreate. Use Rolling only if Che deployment does not use PVC
  value: 'Recreate'
- name: PULL_POLICY
  displayName: Che server image pull policy
  description: Always pull by default. Can be IfNotPresent
  value: 'Always'
- name: CHE_FABRIC8_USER__SERVICE_ENDPOINT
  displayName: User Service Endpoint
  description: URL of the user services API endpoint
  value: '${PROTOCOL}://api-${NAMESPACE}.${ROUTING_SUFFIX}/api/user/services'
- name: CHE_FABRIC8_AUTH_ENDPOINT
  displayName: Auth Service Endpoint
  description: URL of the auth API endpoint
  value: '${PROTOCOL}://auth-${NAMESPACE}.${ROUTING_SUFFIX}'
- name: CHE_FABRIC8_MULTICLUSTER_OSO_PROXY_URL
  displayName: OpenShift Online Proxy Service
  description: URL of the OpenShift Online Proxy service
  value: '${PROTOCOL}://f8osoproxy-${NAMESPACE}.${ROUTING_SUFFIX}'

